version: '3.1'
services:
  db:
    image: postgres:12-alpine
    container_name: "bankApi"
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'bankApi'